### ISSUE TITLE
problem with syntax

### ISSUE THREAD

**Issue by RicardoBATenorio** [scienceopen/pyhwm93#1]
Hi, I'm using your pyhwm93. When I run $ python demo_pyhwm93.py raise:

Traceback (most recent call last):
  File "demo_hwm93.py", line 16, in <module>
    from pyhwm93 import runhwm93
  File "/home/ricardo/pyhwm93/pyhwm93/__init__.py", line 5, in <module>
    from sciencedates import datetime2gtd
  File "/home/ricardo/.local/lib/python2.7/site-packages/sciencedates/__init__.py", line 11
    def datetime2yeardoy(time: Union[str, datetime.datetime]) -> Tuple[int, float]:
                                              ^
SyntaxError: invalid syntax
Could help me to understand what I did wrong?
regards

**Comment by scivision** [comment]
Are you on Python &ge; 3.6?

**Comment by RicardoBATenorio** [comment]
I am using python 2.7
Dr. Michael, the problem was with sciencedates's version, when I installed version 1.2.3 it worked and I got the meridional and zonal wind's plot. Anyways thank you for the help. A last question, how could I extract data? e.g a txt file with wind's values?

**Comment by scivision** [comment]
If you're using the command line script RunHWM93.py, use the `-o` option to write a NetCDF4 (HDF5) file.
As noted in the Readme, the data is returned as an [xarray.Dataset](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.html)
